#version: '3'
#
#services:
#  docker-mysql:
#    image: mysql:latest
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=user_service
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#    ports:
#      - 6603:3306
#
#  app:
#    image: app:latest
#    ports:
#      - 9091:8091
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
#    depends_on:
#      - docker-mysql