version: "3.8"
services:
  user-service-app:
    build: .
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - user-service-db
  user-service-db:
    image: "mysql"
    restart: always
    ports:
      - 6603:3306
    environment:
      MYSQL_DATABASE: user_service
      MYSQL_ROOT_PASSWORD: root